### ISSUE TITLE
Source generated and structured logging.

### ISSUE THREAD

**Issue by antomys** [growthbook/growthbook-c-sharp#31]
To improve the performance of logging (using Microsoft's ILogger<T>) and make logging structured and more readable, proposing:
1. Create partial classes for logging entities;

> Logging [compile-time source generation](https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator) is usually a better alternative to ILogger extension methods like LogInformation. Logging source generation offers better performance, and stronger typing, and avoids spreading string constants throughout your methods. The tradeoff is that using this technique requires a bit more code.

2. Structured logging. Remove string interpolation in logging and introduce message templating:
see: https://medium.com/@stavsofer/structured-logging-and-logs-management-asp-net-core-serilog-seq-61109f740696

**Comment by Norhaven** [comment]
Hi @antomys, thanks for suggesting that! I'm in favor of having structured logging in place, it would definitely help make some more sense of the log output. As far as the compile-time source generation for logs, that would require the SDK to be on at least .Net 5 and it's currently targeting .Net Standard 2.0 (and I strongly suspect that it will stay that way for at least a while due to the desire to support a wider audience) and so that's likely a non-starter.

@darklordzw Are you okay with the PR attached to this issue?
