### ISSUE TITLE
No possibility to set HashVersion for Experiment

### ISSUE THREAD

**Issue by damiangoc-esky** [growthbook/growthbook-c-sharp#37]
In current version of C# SDK there is no possibility to set HashVersion for Experiment.
This property can be set in other SDKs like javascript.
As there is an information in GB documentation about changing default version of hashing to `2` there should be a possibility to set it or it should be the default value.
So my proposition is to set the property of Experiment object regarding to `featureRule.HashVersion` or set that property with default value as `2`.

**Comment by Norhaven** [comment]
Sounds good, thanks for the PR. It's been merged in now, should be in a release soon. Thanks!

**Comment by damiangoc-esky** [comment]
Hi, 
When you plan to do the release?

**Comment by mjr444** [comment]
@Norhaven Hi!

**Are you planning to release this fix very soon?** We have implemented both the SDK JS and SDK C# on the same site. We use the SDK JS to send analytics (assigning IDs and variants), but we need to use the SDK C# to force feature flag values for each variant separately. Currently, the SDK C# assigns flag values from different variants than the SDK JS, causing inconsistencies in our A/B tests due to the v1 hashing in the SDK C#.

We spent several weeks diagnosing why this inconsistency occurred and discovered that the SDK C# is still using v1 hashing. As a result, we have had to halt numerous A/B tests until this fix is released.

Could you provide a timeline for when this fix will be released? **It’s crucial for us to resume our A/B testing as soon as possible**.

Thank you!

**Comment by Norhaven** [comment]
Hi, @mjr444 and @damiangoc-esky, sorry for the delay! I will see if I can get a release out within the next day. Thanks for your patience!

**Comment by Norhaven** [comment]
@mjr444 @damiangoc-esky The 1.0.6 version just released should have the fix. Thanks again!

**Comment by damiangoc-esky** [comment]
You're welcome and also thanks for releasing!
